apiVersion: v1
kind: Service
metadata:
  namespace: nexgear
  name: nexgear-user-module-service
spec:
  selector:
    app: users-module
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8091
  type: LoadBalancer # Or ClusterIP, NodePort, etc.
